custom_users/urls.py
from django.urls import path

from custom_users import controllers, views

urlpatterns = [
    path('login', controllers.auth, name='auth'),
    path('singup', views.CreateUser.as_view(), name='signup'),
    path('logout', controllers.logout, name='logout'),
]

web_secrets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('custom_users.urls', 'custom_users'), namespace='custom_users')),
    path('', include(('file_storage.urls', 'file_storage'), namespace='file_storage'))
]

custom_users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from services import RSA_keys_manipulate


class MyUserManager(BaseUserManager):
    def create_user(self, login, private_key):
        """
        Creates and saves a User with the given login, and keys.
        """

        user = self.model(
            login=login,
            private_key=private_key,
        )

        user.signature = RSA_keys_manipulate.create_signature(private_key=private_key)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, private_key, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            login=login,
            private_key=private_key,
        )
        user.is_admin = True
        user.signature = RSA_keys_manipulate.create_signature(private_key=private_key)
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    login = models.CharField(
        max_length=32,
        unique=True,
    )
    private_key = models.TextField(max_length=4096)
    signature = models.BinaryField()

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = ['private_key']

    def __str__(self):
        return self.login

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

custom_users/forms.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form
from django import forms
from custom_users.models import MyUser
from services import RSA_keys_manipulate


class LoginForm(Form):
    """
        Форма для авторизации пользователя
    """
    current_user = None     # текущий пользователь

    login = forms.CharField(label='Логін',
                            max_length=32)
    public_key = forms.CharField(label='Публічний ключ',
                                 max_length=10240,
                                 widget=forms.Textarea)

    def clean_login(self):
        users = MyUser.objects.filter(login=self.cleaned_data.get('login'))

        if not users:
            raise ValidationError('Введеного логіну немає в системі')

        self.current_user = users[0]
        return users[0].login

    def clean_public_key(self):
        users = MyUser.objects.filter(login=self.cleaned_data.get('login'))

        if users:
            self.current_user = users[0]

            try:
                return self.check_pair()

            except:
                raise ValidationError('Ключ невірний')


        else:
            raise ValidationError('Ключа до неіснуючого логіну немає в системі')

    def check_pair(self):
        public_key_value = self.cleaned_data.get('public_key')
        return RSA_keys_manipulate.check_signature(public_key=public_key_value,
                                                   signature=self.current_user.signature)


class RegisterForm(ModelForm):
    """
        Форма для регистрации пользователя
    """

    class Meta:
        model = MyUser
        fields = ('login', 'private_key')
        labels = {'login': 'Логін',
                  'private_key': 'Приватний ключ'}

    public_key = forms.CharField(label='Публічний ключ',
                                 max_length=10240,
                                 widget=forms.Textarea)

    def clean_public_key(self):
        try:
            return RSA_keys_manipulate.check_keys_valid(public_key=self.cleaned_data.get('public_key'),
                                                        private_key=self.cleaned_data.get('private_key'))
        except:
            raise ValidationError('Невірна зв\'язка ключів, перевірте ключі')

custom_users/controllers.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render, redirect

from custom_users.forms import LoginForm, RegisterForm
from custom_users.models import MyUser
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout


def auth(request: WSGIRequest) -> HttpResponse:

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():

            user = authenticate(request,
                                username=form.cleaned_data['login'],
                                password=form.cleaned_data['public_key'])
            if user:
                login(request, user)

            return redirect('file_storage:file_list')

    else:
        form = LoginForm()

    return render(request, 'custom_users/login.html', {'form': form})


def logout(request: WSGIRequest):
    django_logout(request)
    return redirect('custom_users:auth')

custom_users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView

from custom_users.models import MyUser
from custom_users.forms import RegisterForm
from services import RSA_keys_manipulate


class CreateUser(CreateView):
    model = MyUser
    template_name = 'custom_users/register.html'
    form_class = RegisterForm

    def get_context_data(self, **kwargs):
        context_data = super(CreateUser, self).get_context_data()

        context_data['public_key'], context_data['private_key'] = RSA_keys_manipulate.create_keys()

        return context_data

    def get_success_url(self):
        return reverse('custom_users:auth')

    def form_valid(self, form):
        self.object = form.save()
        self.request.session['custom_user'] = self.object.login
        self.object.signature = RSA_keys_manipulate.create_signature(private_key=self.object.private_key)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

templates/custom_users/login.html
{% extends 'simple_create_form.html' %}
{% load static %}

{% block extra_buttons %}
    <link rel="stylesheet" href="{% static 'css/custom_users/login.css' %}">
    <div class="reg_info shadow_border">
        <p>Не маєте облікового запису?</p>
        <a class="shadow_border" href="{% url 'custom_users:signup' %}">Зареєструйтесь 😊</a>
    </div>
{% endblock %}

templates/custom_users/register.html
{% extends 'simple_create_form.html' %}
{% load static %}

{% block extra_buttons %}
    <link rel="stylesheet" href="{% static 'css/custom_users/register.css' %}">

    <div id="key_info" class="key_info shadow_border">
        <p>Якщо ви не знаєте правил генерування ключів, можете скористатися кнопкою нижче, вам відразу надасться 2 ключі, які ви зможете використовувати в системі, ключі будуть згенеровані випадково</p>
        <div class="key_generate blue_button shadow_border">Згенерувати ключі 🔑</div>
        <div class="keys">
            <p class="help">(Клацніть на ключ, щоб скопіювати)</p>
            <div class="public_key___info shadow_border">
                <p class="public_key___suggestion">
                    Цей ключ необхідно зберегти, тому що по ньому проходитиме авторизація
                </p>
                <div class="public_key shadow_border">{{ public_key }}</div>
            </div>
            <div class="private_key shadow_border">{{ private_key }}</div>
            <div class="keys___paste_keys blue_button shadow_border">
                Копіювати ключі у поля введення 📝,<br>а публічний ключ скопіювати в буфер обміну ⌨️
            </div>
        </div>
    </div>

    <div class="keys_popup shadow_border">
        <span class="close"></span>
        <p class="keys_popup___text">
            Ключ успішно скопійовано! ☺️
        </p>
    </div>

    <script src="{% static 'js/custom_users/register.js' %}"></script>
{% endblock %}