custom_users/urls.py
from django.urls import path

from custom_users import controllers, views

urlpatterns = [
    path('login', controllers.auth, name='auth'),
    path('singup', views.CreateUser.as_view(), name='signup'),
    path('logout', controllers.logout, name='logout'),
]

web_secrets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('custom_users.urls', 'custom_users'), namespace='custom_users')),
    path('', include(('file_storage.urls', 'file_storage'), namespace='file_storage'))
]

templates/form.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">


<form
        method="post"
        {% if upload_file %}enctype="multipart/form-data"{% endif %}
        {% if next_url %}action="{{ next_url }}"{% endif %}
        class="shadow_border"
        novalidate
>
    {% csrf_token %}

    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="row">
            <div class="title_row {% if field.errors %}error_field_label swing{% endif %}">
                {{ field.label }}
            </div>
            <div class="field_value {% if field.errors %}error_field swing{% endif %}">
                {{ field }}
            </div>
            <div class="errors">
                {{ field.errors }}
            </div>
        </div>
    {% endfor %}

    <input type="submit" value="Надіслати">
</form>

templates/header.html
{% load static %}

<div class="header">

    {% if auth %}
        <div class="right_menu">
            <a href="{% url 'custom_users:logout' %}" class="logout_url shadow_border">
                <img class="logout_icon" src="{% static 'icons/logout.svg' %}" alt="">Вийти
            </a>
        </div>
    {% endif %}

</div>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/shadow_border.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500&display=swap" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'header.html' %}

     <div class="container">
         {% block body %}
         {% endblock %}
    </div>

{#    {% include 'popup.html' %}#}
    {% block scripts %}

    {% endblock %}
</body>
</html>

templates/simple_create_form.html
{% extends 'main.html' %}
{% load static %}

{% block page_title %}
    {{ tab_title }}
{% endblock %}


{% block body %}
{#    {% include 'breadcrumbs.html' %}#}

    {% include 'form.html' %}

    {% block extra_buttons %}

    {% endblock %}
{% endblock %}