file_storage/urls.py
from django.conf.urls.static import static
from django.urls import path

from file_storage import views, controllers
from web_secrets import settings

urlpatterns = [
    path('', views.FileList.as_view(), name='file_list'),
    path('load_file', controllers.load_file, name='load_file'),
    path('download_file/<int:file_id>', controllers.download_file, name='file')
]

web_secrets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('custom_users.urls', 'custom_users'), namespace='custom_users')),
    path('', include(('file_storage.urls', 'file_storage'), namespace='file_storage'))
]

file_storage/models.py
from django.db import models
from django.utils.safestring import mark_safe

from custom_users.models import MyUser
from web_secrets.settings import PATH_TO_USERS_FILES


class File(models.Model):
    user = models.ForeignKey(MyUser,
                             on_delete=models.CASCADE)
    filename = models.CharField(max_length=64,
                                blank=True)
    filesize = models.FloatField()
    upload_date = models.DateTimeField(auto_now=True)
    file = models.FileField(upload_to=PATH_TO_USERS_FILES)

    def __str__(self):
        return '; '.join((self.user.login,
                          self.filename,
                          str(self.filesize) + 'MB',))

    def fieldname_download(self):
        return mark_safe('<a href="/download_file/{0}">{1}</a>'
                         .format(self.id, self.filename))

    fieldname_download.short_description = 'Завантажений файл'

file_storage/controllers.py
import os.path

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import redirect
from django.http.response import HttpResponse, FileResponse

from file_storage.models import File
from web_secrets.settings import MEDIA_ROOT


def load_file(request: WSGIRequest):
    file = request.FILES['file_load']
    File(user=request.user,
         file=file,
         filename=file.name,
         filesize=round(file.size / 1024 / 1024, 2)).save()
    return redirect('file_storage:file_list')


def download_file(request: WSGIRequest, file_id: int):
    if files := File.objects.filter(id=file_id):
        file = files[0]
        if request.user.is_admin or file.user == request.user:
            return FileResponse(open(os.path.join(MEDIA_ROOT, file.file.name), 'rb'),
                                filename=file.filename)

    return HttpResponse(status=404)

file_storage/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView
from file_storage.models import File
from web_secrets import settings


class FileList(LoginRequiredMixin, ListView):
    model = File
    paginate_by = 10
    template_name = 'file_storage/file_list.html'
    context_object_name = 'files'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super(FileList, self).get_context_data()
        context_data['max_file_size'] = settings.MAX_FILE_SIZE
        context_data['auth'] = True
        return context_data

    def get_queryset(self):
        return File.objects.filter(user=self.request.user)

templates/file_storage/file_list.html
{% extends 'main.html' %}
{% load static %}

{% block page_title %}
    {{ tab_title }}
{% endblock %}


{% block body %}
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/file_storage/file_list.css' %}">

    <table class="files_table">
        {% if files %}
            <tr>
                <th>Назва</th>
                <th>Розмір</th>
                <th>Дата Завантаження</th>
            </tr>
            {% for file in files %}
                <tr>
                    <td>
                        <a href="{% url 'file_storage:file' file.id %}">{{ file.filename }}</a>
                    </td>
                    <td>
                        <a href="{% url 'file_storage:file' file.id %}">{{ file.filesize }} MB</a>
                    </td>
                    <td>
                        <a href="{% url 'file_storage:file' file.id %}">{{ file.upload_date }}</a>
                    </td>
                </tr>
            {% endfor %}

            {% if page_obj.paginator.num_pages > 1 %}

                <tr>
                    <td>
                        {% if page_obj.has_previous %}
                            <a class="paginator_url" href="?page={{ page_obj.previous_page_number }}">⏪</a>
                        {% endif %}
                    </td>
                    <td>
                        {{ page_obj.number }} з {{ page_obj.paginator.count }}
                    </td>
                    <td>
                        {% if page_obj.has_next %}
                            <a class="paginator_url" href="?page={{ page_obj.next_page_number }}">⏩</a>
                        {% endif %}
                    </td>
                </tr>

            {% endif %}

        {% else %}

            <tr>
                <td>
                    Немає файлів
                </td>
            </tr>

        {% endif %}
        <tr>
            <td colspan="3">
                <div class="load_file">
                    <form action="{% url 'file_storage:load_file' %}"
                          enctype="multipart/form-data"
                          method="post"
                          novalidate>
                        {% csrf_token %}
                        <label for="file_load" class="label_file_load blue_button shadow_border">Завантажити файл</label>
                        <input id="file_load" name="file_load" type="file">
                        <input type="submit" class="blue_button shadow_border submit_file" value="Надіслати" disabled>
                    </form>
                </div>
            </td>
        </tr>
    </table>

    <script>const max_file_size = {{ max_file_size }}</script>
    <script src="{% static 'js/file_storage/load_file.js' %}"></script>
{% endblock %}